#!/bin/bash

set -e

readonly CURRENT_PATH="$( cd "$( dirname "$0" )" && pwd )"

# default parameters
DBHOST=${PGHOST}
DBPORT=${PGPORT:-5432}
DBUSER=${PGUSER}
DATABASE=${PGDATABASE}

DISABLE_PROMPT=0

function help {
    cat <<EOF
pg-patch is a utility for patching database and tracking patches.

usage: pg-patch <command> [--help]
                [-c file] [-h host] [-p port] [-U user] [-d database]

Available commands are:
  install  Installs pg-patch to database
  add      Create new patch from template
  list     List local, applied or both local and applied (default) patches
  deploy   Deploy all available patches
  sql      Output SQL commands for patching database
  dot      Outputs local patches in Graphviz dot format

To see help related to command use:
  pg-patch <command> --help

All commands except 'add' require a connection target DB.
Default options could be set in default.conf file (see default.conf.example).
You can supply your own config file with '-c' option.

Common options (for all commands, except 'add'):
  -c --config <file>   read options from config file
  -h --host <host>     target host name
  -p --port <port>     database server port name
  -U --user <user>     database user
  -d --database <db>   target database name
  -y --yes             disable the confirmation prompt

Usage examples:
  ./pg-patch add second-patch first-patch
  ./pg-patch list
  ./pg-patch deploy -c test_db.conf
EOF
}


function grep_bin() {
    if [[ ${OSTYPE//[0-9.]} == "solaris" ]]; then
        ggrep "$@"
    else
        grep "$@"
    fi
}


function read_input() {
    local default_val=$1
    local message=$2
    local input_val=$3

    if [ "$input_val" = '' ]; then
        [[ $DISABLE_PROMPT -eq 0 ]] && read -p "$message" input_val
        input_val=${input_val:-$default_val}
    fi
    echo $input_val
}


function read_config() {
    local config=$1
    local mandatory=${2:-'optional'} # 'mandatory' or 'optional'
    local tmp_config="/tmp/sr_db.$$.conf"

    # echo "reading config: $1, mandatory: $mandatory"

    # print help if only command is specified and config not found
    if [[ "$mandatory" == 'mandatory' ]] && [[ ! -f $config ]] ; then
        echo "ERROR:  config file '$config' not found. See 'pg-patch --help'." 1>&2
        exit 1
    fi

    if [[ -f $config ]] ; then
        # clear tmp file
        :> $tmp_config
        # remove dangerous stuff
        sed -e 's/#.*$//g;s/;.*$//g;/^$/d' $config |
            while read line
            do
                if echo $line | grep_bin -F = &>/dev/null
                then
                    echo "$line" >> $tmp_config
                fi
            done
        . $tmp_config
        rm $tmp_config
    fi
    return 0
}


function check_command() {
    case "$1" in
        help)             help && exit 0;;
        --help)           help && exit 0;;
        list)             PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/list.sh" ;;
        sql)              PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/sql.sh" ;;
        deploy)           PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/deploy.sh" ;;
        install)          PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/install.sh" ;;
        add)              PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/add.sh" ;;
        dot)              PGPATCH_COMMAND=$1; COMMAND_SCRIPT="$CURRENT_PATH/tools/sh/dot.sh" ;;
        # error, if anything else
        *)                if [[ -z "$1" ]] ; then
                              help
                              exit 0
                          fi
                          echo "ERROR:  '$1' is not a valid command. See 'pg-patch --help'." 1>&2
                          exit 1
                          ;;
    esac
}


function long_to_short_options() {
    # translate --gnu-long-options to -g (short options)
    # for all possible commands
    local args=()
    local arg=
    for arg; do
        case "$arg" in
            # --help)           help && exit 0;;
            --help)           HELP_FLAG=$arg ;;
            --config)         args+=( -c ) ;;
            --host)           args+=( -h ) ;;
            --port)           args+=( -p ) ;;
            --user)           args+=( -U ) ;;
            --database)       args+=( -d ) ;;
            # rest
            --dry-run)        args+=( -0 ) ;; # for deploy & sql
            --install)        args+=( -i ) ;; # for deploy & sql
            --silent)         args+=( -s ) ;; # for list & sql
            --yes)            args+=( -y ) ;; # for deploy
            --verbose)        args+=( -v ) ;; # for deploy
            --both)           args+=( -b ) ;; # for list
            --local)          args+=( -l ) ;; # for list
            --applied)        args+=( -a ) ;; # for list
            # error out if we encounter other --unknown commands
            --*)              echo "ERROR:  illegal option '$arg'. See 'pg-patch --help'." 1>&2; exit 1; ;;
            *)                args+=( "$arg" ) ;;
        esac
    done

    SHORT_OPTIONS=("${args[@]}")

    return 0
}


function read_common_db_args() {
    # read config / DB connection parameters (for all commands)
    local unprocessed_args=() # init. pass-through array
    while getopts ":c:h:p:U:d:y" optname
    do
        case "$optname" in
            "c") param_config=$OPTARG;;
            "h") param_dbhost=$OPTARG ;;
            "p") param_dbport=$OPTARG ;;
            "U") param_dbuser=$OPTARG ;;
            "d") param_database=$OPTARG ;;
            "y") param_disable_prompt=1 ;;
            ":") echo "ERROR:  option '-$OPTARG' requires an argument. See 'pg-patch --help'." 1>&2
                 exit 1
                 ;;
            *) # pass-thru option, possibly followed by an argument
                  unprocessed_args+=( "-$OPTARG" ) # add to pass-through array
                  # see if the next arg is an option, and, if not,
                  # add it to the pass-through array and skip it
                  if [[ ${@: OPTIND:1} != -* ]]; then
                    unprocessed_args+=( "${@: OPTIND:1}" )
                    (( ++OPTIND ))
                  fi
                  ;;
        esac
    done
    shift $((OPTIND - 1))
    unprocessed_args+=( "$@" )  # append remaining args. (operands), if any
    
    PASS_THROUGH_ARGS=("${unprocessed_args[@]}")

    return 0
}


function deal_with_missing_args() {
    # Defaults
    local default_host='localhost'
    local default_port='5432'
    local default_dbuser='postgres'
    local default_dbname='demodb'

    # process parameters

    # server host
    DBHOST=$(read_input "$default_host" "Enter destination hostname [$default_host]: " "$DBHOST")

    # server port
    DBPORT=$(read_input "$default_port" "Enter destination port [$default_port]: " "$DBPORT")

    # database user
    DBUSER=$(read_input "$default_dbuser" "Enter destination user [$default_dbuser]: " "$DBUSER")

    # database
    DATABASE=$(read_input "$default_dbname" "Enter destination database [$default_dbname]: " "$DATABASE")

    return 0
}


function main() {
    local PGPATCH_COMMAND=
    local COMMAND_SCRIPT=
    # check if command is valid
    check_command "$@"

    # shortened args stored here
    local HELP_FLAG=
    local SHORT_OPTIONS=()
    long_to_short_options "${@:2}"

    # display help for commands
    if [[ -n $HELP_FLAG ]] ; then
        $COMMAND_SCRIPT '--help'
        exit 0
    fi;

    # run commands that can be run without db connection
    if [[ "$PGPATCH_COMMAND" == 'add' ]] ; then
        $COMMAND_SCRIPT "${SHORT_OPTIONS[@]}"
        exit 0
    fi


    # echo "SHORT_OPTIONS: ${SHORT_OPTIONS[@]}"

    local param_config=
    local param_dbhost=
    local param_dbport=
    local param_dbuser=
    local param_database=
    local param_disable_prompt=
    local PASS_THROUGH_ARGS=()

    read_common_db_args "${SHORT_OPTIONS[@]}"

    # echo "param_config: $param_config"
    # echo "param_dbhost: $param_dbhost"
    # echo "param_dbport: $param_dbport"
    # echo "param_dbuser: $param_dbuser"
    # echo "param_database: $param_database"
    # echo "PASS_THROUGH_ARGS: ${PASS_THROUGH_ARGS[@]}"

    # load configs, in this order
    # ./default.conf -> ~/.pg-patch.conf -> the one supplied via option (if present)
    read_config "$CURRENT_PATH/default.conf" 'optional'
    read_config "~/.pg-patch.conf" 'optional'
    
    if [[ -n "$param_config" ]] ; then
        read_config "$param_config" 'mandatory'
    fi
    
    # command-line params override values set in configs
    DBHOST=${param_dbhost:-$DBHOST}
    DBPORT=${param_dbport:-$DBPORT}
    DBUSER=${param_dbuser:-$DBUSER}
    DATABASE=${param_database:-$DATABASE}
    DISABLE_PROMPT=${param_disable_prompt:-$DISABLE_PROMPT}

    deal_with_missing_args

    # echo "-- Final db params to pass:"
    # echo "--   DBHOST:   $DBHOST"
    # echo "--   DBPORT:   $DBPORT"
    # echo "--   DBUSER:   $DBUSER"
    # echo "--   DATABASE: $DATABASE"

    # run commands that require db connection
    local command_db_args="-h $DBHOST -p $DBPORT -U $DBUSER -d $DATABASE"

    if [[ "$PGPATCH_COMMAND" == 'deploy' && $DISABLE_PROMPT -ne 0 ]] ; then
        $COMMAND_SCRIPT "$command_db_args" "${PASS_THROUGH_ARGS[@]}" '-y'
    else
        $COMMAND_SCRIPT "$command_db_args" "${PASS_THROUGH_ARGS[@]}"
    fi
    
    exit 0
}

main "$@"
